DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
		ID BIGINT AUTO_INCREMENT PRIMARY KEY,
        FIRST_NAME VARCHAR(50) NOT NULL,
        LAST_NAME VARCHAR(50) NOT NULL,
        EMAIL VARCHAR(50) NOT NULL,
        POSITION_TITLE VARCHAR(50) NOT NULL,
        SALARY_ENCRYPTED VARCHAR(50) NOT NULL,
        SALARY_ENCRYPTED_NONCE VARCHAR(20) NOT NULL,
        UNIQUE KEY EMAIL_UNIQUE (EMAIL)
	);